<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Priyatharsan_D" failures="1" tests="6" name="Default test(failed)" time="0.079" errors="0" timestamp="2024-12-30T16:46:25 IST">
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.021">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.advSelenium.Listeners.RetrySample" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.advSelenium.Listeners.RetrySample.test1(RetrySample.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
